### ISSUE TITLE
Request Minify Version

### ISSUE THREAD

**Issue by makmizi15** [oberonamsterdam/horizontal#16]
Would love to have access to the minify version so I can utilize this on my webflow site

**Comment by tlorent** [comment]
Hi @makmizi15 ,

Our apologies for our late reply and thank you for showing interest in our horizontal package!

We are currently working on your request. Please note that this might take a while for us to complete. Thank you for your patience!

**Comment by makmizi15** [comment]
You guys are so amazing! Thank you!!!

**Comment by kheiraoudejans** [comment]
Hi @makmizi15 
Sorry it took so long, but the minify version has finally been released! 
Just don't forget to install rebound package: https://www.npmjs.com/package/rebound

Good luck!
