### ISSUE TITLE
"TypeError: Cannot read property '_events' of undefined"

### ISSUE THREAD

**Issue by metacryst** [oberonamsterdam/horizontal#17]
I am using Chrome and React - and I get this message upon trying to run the app.

```
TypeError: Cannot read property '_events' of undefined
push../node_modules/events/events.js.EventEmitter.init
node_modules/events/events.js:90
  87 | 
  88 | EventEmitter.init = function() {
  89 | 
> 90 |   if (this._events === undefined ||
  91 |       this._events === Object.getPrototypeOf(this)._events) {
  92 |     this._events = Object.create(null);
  93 |     this._eventsCount = 0;
View compiled
EventEmitter
node_modules/events/events.js:54
  51 | }
  52 | 
  53 | function EventEmitter() {
> 54 |   EventEmitter.init.call(this);
  55 | }
  56 | module.exports = EventEmitter;
  57 | 
```

top of my App component:
```
import useHorizontal from '@oberon-amsterdam/horizontal';

import "./App.css";

import Arts from "./components/Arts.js"
import Art from "./components/Art.js"

import SignIn from './components/SignIn';
import SignUp from './components/SignUp';
import User from './components/User';

import About from "./components/About"




function App() {
  
  
  useHorizontal();
```

I can show more code if you want, but I can't imagine anything in there would be breaking it.

**Comment by jariz** [comment]
@metacryst Hi, I can't seem to replicate this.
Is there any chance you could set up a repo / codesandbox that replicates this?

**Comment by metacryst** [comment]
for sure! here's a link to a fork of the repo:

[https://github.com/metacryst/wip-front](url)

just clone it down, install react-router, react-router-dom, and your horizontal package, it should run. and then if you go into the app.js and uncomment the useHorizontal() part at the very top it should produce the error.

**Comment by tlorent** [comment]
Hi @metacryst ,

Thank you for sharing your repo. We will have a look at your code and report back to you when we have found a solution. Please note that this might take a little while.

Thank you for your patience!

**Comment by tlorent** [comment]
Hi @metacryst ,

Apparently your code returns an undefined `document` somewhere. This means that the event listeners in the `useHorizontal` hook can't be set, which is presumably why you get the "_events of undefined" error. We have spent some time on your issue today, but we have not yet figured out why this happens. 

Furthermore, this is a friendly tip: open up your console and you should see that your code triggers an infinite loop (a huge number of errors get logged every second).

We will keep you updated on our progress!

**Comment by matthijsoberon** [comment]
Hey @metacryst,

Sorry for not getting back to you earlier!
I've just checked out your repo to see what is going on and the first thing I noticed is that you imported the "useHorizontal" hook in the wrong way, see: https://github.com/oberonamsterdam/horizontal#react-hook
You should import it as `import useHorizontal from '@oberon-amsterdam/horizontal/hook';` instead of `import useHorizontal from '@oberon-amsterdam/horizontal`.
Let me know if this solves your issue so you can keep working with the horizontal package!
