### ISSUE TITLE
iOS can scroll horizontally and Android can scroll horizontal and vertical

### ISSUE THREAD

**Issue by NASlR** [oberonamsterdam/horizontal#18]
Hi, thanks for the project and am looking forward to trying it. 

It seems that on desktop it scrolls horizontally as intended

But on mobile it can go both ways. I tried your codesandbox on my devices and the issue occurs

set the block min-width to 100

on ios: scroll horizontal
on android: scroll vertical - see yellow body, scroll horizontal - see blocks

I thought on mobile, horizontal should be disabled and the elements reorder themselves to be vertical. 

Any ideas?

Thanks :)

**Comment by tlorent** [comment]
Hi @NASlR ,

Thank your for reporting this issue, we will look into this. Please note that it might take a little while.

Thank you for your patience!

**Comment by MokumJ** [comment]
Hi Nasir,

On what sandbox is this issue occurring?
An example with a container or without? And the react version or vanilla?
We are having troubles reproducing your issue.

Please note that on the container version vertical scroll outside the container is aloud and expected behaviour. Please make sure when scrolling that you are scrolling within the container.

Hope that we can help you further.

**Comment by NASlR** [comment]
Hi, sorry it's been a while - at the time I should've said clearer what was going on

The [react sample sandbox](https://codesandbox.io/s/github/oberonamsterdam/horizontal/tree/master/examples?module=/react.jsx&initialpath=react.html&file=/style.css) is the one where I noticed the issue

If you run the sandbox on mobile. Should each block 'Hello, scroll further', 'Why, hello there' etc. etc. not scroll downwards? On my iPhone when I look run the sandbox I can still scroll horizontally but I thought that it should automatically reorder to be vertical on mobile

**Comment by tlorent** [comment]
Hi @NASlR ,

Thank you for your reply. 

Unfortunately, the switch to vertical scrolling is not supported in our package. If you require this feature then you can either request it by adding a new issue or creating it yourself and adding a PR (might be a fun challenge!) 😃 . We will close this issue for now.

Kind regards,

Oberon
