### ISSUE TITLE
Can't reach the end of the page

### ISSUE THREAD

**Issue by arguiot** [oberonamsterdam/horizontal#25]
When using a mouse and scrolling (fast), you can't reach the end of the page. This issue is probably caused by the following `if` statement:
https://github.com/oberonamsterdam/horizontal/blob/bf5e888dbc6b7e1c3a1d2e5f0857e06d7440d789/src/index.ts#L179

When the distance is superior to the page/container width the scrolling action is dismissed, where it **should** be taken into account. To fix the issue, an `else` statement can be added to simply set the scroll to the maximum value (100% scroll).

I'm not opening a PR because I don't know how to do that, but since it seems easy to fix I hope this issue will be fixed quickly 😁.

**Comment by maximedaoust** [comment]
@arguiot Funny I was about to create an issue. I was testing multiple horizontal navigation solutions and I hit the exact same bug (on Windows with a mouse wheel) :)

Another possible solution would to take the SCROLL_AMOUNT into consideration. something like : 
`if (distance - SCROLL_AMOUNT < _this.container.scrollWidth - _this.container.clientWidth) {`

**Comment by arguiot** [comment]
Not sure I fully understand the difference between `distance` and `SCROLL_AMOUNT`, but if you think it works, let's test it to see which solution is the most appropriate!

**Comment by arguiot** [comment]
@maximedaoust  Actually, I just tested on Safari (macOS Big Sur) and it seems to work quite well. Do you want to open a PR? (if you don't have the time to, I can do it, but it's your solution after all...)
