### ISSUE TITLE
scrollIntoView wheel start scroll from beginning than jump to current.

### ISSUE THREAD

**Issue by WandererInVoids** [oberonamsterdam/horizontal#27]
After  scrollIntoView  function. wheel start scroll from beginning than jump to current.
Solution   

https://github.com/oberonamsterdam/horizontal/blob/bf5e888dbc6b7e1c3a1d2e5f0857e06d7440d789/src/index.ts#L177
`this.spring.setCurrentValue(this.container.scrollLeft);` put after this for initial spring. Or listen for scroll event in container

**Comment by matthijsoberon** [comment]
Hey! 
Sorry for not getting back to you earlier, but do you have any example/codepen of this? Im not sure what's going on in this issue.

**Comment by matthijsoberon** [comment]
Closing this due to no recent activities. Feel free to open it again if you want :).
