### ISSUE TITLE
Support Google maps

### ISSUE THREAD

**Issue by Mark-Hetherington** [oberonamsterdam/horizontal#28]
Google maps uses a ctrl+scrollwheel event to zoom in and out, without hijacking the standard scroll event. 

If we ignore scroll wheel when ctrl is pressed, this will prevent both the horizontal scroll and map handling the scroll. It will also allow the ctrl+wheel to control zoom in Chrome.

**Comment by matthijsoberon** [comment]
Thanks for contributing, I based my PR #33 on yours with some minor changes.
