### ISSUE TITLE
Get Scroll Position of Container using Hook?

### ISSUE THREAD

**Issue by phil-kt** [oberonamsterdam/horizontal#48]
How can I grab the scroll position of the scrolling container if I'm using the Hook example?

The README has an example for when you instantiate an instance of HorizontalScroll:

```
const horizontal = new HorizontalScroll()
horizontal.on('scroll', fn)
```

But if I use the hook I don't get an object back, so wondering how I would get the position of a nested div for example:
```
const [container, setContainer] = React.useState()
useHorizontal({ container: container })

return (
    <div>
        <div className="container" ref={ref => {setContainer(ref);}}>
        </div>
    </div>
)
```

Still a n00b to hooks so this may be a simple question, thanks if you can help!

**Comment by phil-kt** [comment]
just bumping if y'all can help

**Comment by jariz** [comment]
You use the container ref that horizontal itself uses also. This contains a reference to the underlying `HTMLElement` that horizontal itself also uses.

Then, you access the scroll offset through normal means, e.g. 

```js
container.current.scrollLeft
// or
container.current.scrollTop
```

**Comment by phil-kt** [comment]
gotcha, it was throwing me off as container was returning what looked like the innerHTML element vs a ref object with a current key when I was console.log'ing it, so didn't know I could call `.current` on it

**Comment by phil-kt** [comment]
hmm @jariz doesn't seem to work, I just get `Cannot read property 'scrollLeft' of undefined` as it seems container is the raw `innerHTML` element and not a ref, so it doesn't have a current property

e.g.
```
const [container, setContainer] = React.useState()
useHorizontal({ container: container })
if(container) {
  console.log(container.current.scrollLeft)
}

return (
<div>
      <div ref={ref => {setContainer(ref);}}>
          <h1>hi</h1>
      </div>
</div>
)
```

that `console.log` gives me an error, and if I` console.log` just `container` I get
```
<div>
     <h1>hi</h1>
</div>
```
